application: millamatkaan
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: main.gae_app


libraries:
- name: lxml
  version: latest

builtins:
- deferred: on
